#ifndef SHARED_PBRMATERIAL_H
#define SHARED_PBRMATERIAL_H

#define SL_ALBEDO_SLOT 0
#define SL_NORMAL_SLOT 1
#define SL_EMISSIVE_SLOT 2
#define SL_ORM_SLOT 3

// #define SL_MODEL_LOCATION 0
// #define SL_MODEL_INV_TRANS_LOCATION 1
#define SL_USE_ALBEDO_TEXTURE_LOCATION 2
#define SL_USE_NORMAL_TEXTURE_LOCATION 3
#define SL_USE_EMISSIVE_TEXTURE_LOCATION 4
#define SL_USE_OCCLUSION_TEXTURE_LOCATION 5
#define SL_USE_ROUGHNESS_TEXTURE_LOCATION 6
#define SL_USE_METALLIC_TEXTURE_LOCATION 7
#define SL_ALBEDO_FACTOR_LOCATION 8
#define SL_NORMAL_FACTOR_LOCATION 9
#define SL_EMISSIVE_FACTOR_LOCATION 10
#define SL_OCCLUSION_FACTOR_LOCATION 11
#define SL_ROUGHNESS_FACTOR_LOCATION 12
#define SL_METALLIC_FACTOR_LOCATION 13
// TODO: Tilling uniform locations.

#define SL_REFLECTANCE_LOCATION 20

// TODO: Can I get these from SPIRV?

#endif
