#ifndef SL_SHARED_PBRMATERIAL_H
#define SL_SHARED_PBRMATERIAL_H

#define SL_SLOT_ALBEDO 0
#define SL_SLOT_NORMAL 1
#define SL_SLOT_EMISSIVE 2
#define SL_SLOT_ORM 3

// #define SL_LOCATION_MODEL 0
// #define SL_LOCATION_MODEL_INV_TRANS 1
#define SL_LOCATION_USE_ALBEDO_TEXTURE 2
#define SL_LOCATION_USE_NORMAL_TEXTURE 3
#define SL_LOCATION_USE_EMISSIVE_TEXTURE 4
#define SL_LOCATION_USE_OCCLUSION_TEXTURE 5
#define SL_LOCATION_USE_ROUGHNESS_TEXTURE 6
#define SL_LOCATION_USE_METALLIC_TEXTURE 7

#define SL_LOCATION_ALBEDO_FACTOR 8
#define SL_LOCATION_NORMAL_FACTOR 9
#define SL_LOCATION_EMISSIVE_FACTOR 10
#define SL_LOCATION_OCCLUSION_FACTOR 11
#define SL_LOCATION_ROUGHNESS_FACTOR 12
#define SL_LOCATION_METALLIC_FACTOR 13

#define SL_LOCATION_ALBEDO_TILLING 14
#define SL_LOCATION_NORMAL_TILLING 15
#define SL_LOCATION_EMISSIVE_TILLING 16
#define SL_LOCATION_OCCLUSION_TILLING 17
#define SL_LOCATION_ROUGHNESS_TILLING 18
#define SL_LOCATION_METALLIC_TILLING 19

#define SL_LOCATION_REFLECTANCE 20
#define SL_LOCATION_TWO_SIDE 21

// TODO: Can I get these from SPIRV?

#endif
